### ISSUE TITLE
Enable CSS Modules

### ISSUE THREAD

**Issue by nahue** [FormAPI/craco-less#1]
Is it hard to enable CSS Modules? if you point out where to do it.. i can build a PR for you.

**Comment by ndbroadbent** [comment]
Hi @nahue, sorry that was a huge oversight on my part! I only made it possible to configure the `less-loader` in the first version.

I've just updated the plugin so that you can configure CSS modules with `css-loader`. I've added a new [Configuration](https://github.com/FormAPI/craco-less#configuration) section to the README, and also a section that shows [how to configure CSS modules](https://github.com/FormAPI/craco-less#css-modules). 

You have to careful about this [CSS modules gotcha](https://github.com/FormAPI/craco-less#css-modules-gotcha) though. I saw that while reading the less-loader documentation.

These changes were released in version `1.2.0`. Please let me know if that works for you!

**Comment by CuddleBunny** [comment]
Is there a way to support both modules and non-modules? It looks like the pattern `/\.module\.(less)$/` is excluded. I tried something like the following, but am not quite sure how to configure the `modifyLessRule` option:

```
const CracoLessPlugin = require("craco-less");

module.exports = {
  plugins: [
    {
      plugin: CracoLessPlugin
    },
    {
      plugin: CracoLessPlugin,
      options: {
        modifyLessRule: function(lessRule, context) {
          return { 
            test: /\.module\.(less)$/
          }
        },
        cssLoaderOptions: {
          modules: true,
          localIdentName: "[local]_[hash:base64:5]"
        }
      }
    }
  ]
};
```

**Comment by zechau** [comment]
> Is there a way to support both modules and non-modules? It looks like the pattern `/\.module\.(less)$/` is excluded. I tried something like the following, but am not quite sure how to configure the `modifyLessRule` option:
> 
> ```
> const CracoLessPlugin = require("craco-less");
> 
> module.exports = {
>   plugins: [
>     {
>       plugin: CracoLessPlugin
>     },
>     {
>       plugin: CracoLessPlugin,
>       options: {
>         modifyLessRule: function(lessRule, context) {
>           return { 
>             test: /\.module\.(less)$/
>           }
>         },
>         cssLoaderOptions: {
>           modules: true,
>           localIdentName: "[local]_[hash:base64:5]"
>         }
>       }
>     }
>   ]
> };
> ```
> 
> EDIT: I got it to work with the following changes to config:
> 
> ```
> const CracoLessPlugin = require("craco-less");
> 
> module.exports = {
>   plugins: [    
>     {
>       plugin: CracoLessPlugin
>     },
>     {
>       plugin: CracoLessPlugin,
>       options: {
>         modifyLessRule: function(lessRule, _context) {
>           lessRule.test = /\.(module)\.(less)$/;
>           lessRule.exclude = /node_modules/;
> 
>           return lessRule;
>         },
>         cssLoaderOptions: {
>           modules: true,
>           localIdentName: "[local]_[hash:base64:5]"
>         }
>       }
>     }
>   ]
> };
> ```

It works for me!
