### ISSUE TITLE
LESS output is always bundled into JS

### ISSUE THREAD

**Issue by duhseekoh** [FormAPI/craco-less#2]
For CSS and SASS in create-react-app 
- development build (`npm start`), the css is bundled with the `js` files.
- production build (`npm build`) , the css is chunked out into `css` files.

While using this plugin, the css is **always** bundled with the `js` files. Ideally this less plugin functions the same way the sass loader in CRA does, which would include extracting CSS from the js bundle and including it in css files.

**Comment by duhseekoh** [comment]
For some more context, the common function used to gather the necessary loaders for each css preprocessor.
```const getStyleLoaders = (cssOptions, preProcessor) => {```
rest at https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L79

**Comment by ndbroadbent** [comment]
Hi @duhseekoh, sorry about that! I should have checked that earlier. I'll try to fix that soon so that CSS is extracted in production

**Comment by duhseekoh** [comment]
No problem. Thanks for the package.

I was thinking, one interesting way to solve this particular issue, and to keep it entirely in sync with how the set of loaders supporting sass in official CRA work, is to...
1. have this plugin find and copy the sass loader section (output of `getStyleLoader`)
2. in that copy, just replace the `sass-loader` for `less-loader`
3. push that copy into the list of loaders (before file-loader)

**Comment by ndbroadbent** [comment]
Yeah I really like that idea. I'm also using this upstream in the [craco-antd](https://github.com/FormAPI/craco-antd) plugin, so I'll have to rethink the [loader options](https://github.com/FormAPI/craco-antd#loader-options). I think should just accept a callback so that the user can modify whatever they need.

**Comment by OshotOkill** [comment]
I've written a function to enable `less-loader` in [customize-cra](https://github.com/arackaf/customize-cra), struggling with two different modes (dev & prod) for a while but finally it gets to work. So I think this might be a help.

**Comment by ndbroadbent** [comment]
Hi, sorry about this issue, and sorry for the delay! This was a huge oversight, because I totally forgot to check production builds.

@OshotOkill thanks, that was really helpful!

@duhseekoh I followed your suggestion to copy the `sass-loader` rule from the webpack config, and just replace `sass-loader` with `less-loader`. This works really well, and it sets up `mini-css-extract-plugin` in production so that CSS is now extracted to the separate file.

I've also created a new production test suite, so now there's 100% test coverage for both development and production builds.

This has been released in version `1.3.0`, so please let me know if you run into any issues. Thanks!

**Comment by duhseekoh** [comment]
Awesome thanks. Will check it out this week.
