### ISSUE TITLE
craco-less install different version of webpack when "npm install"

### ISSUE THREAD

**Issue by MmmmyPh** [FormAPI/craco-less#3]
When create a new app by steps:
```
1.  create-react-app demo
2.  npm install @craco/craco craco-less
3.  npm start
```
It goes fine, the app runs.
Then I push this to git or delete `node_modules` and `package-lock.json`, then run:
```
1. npm install
2. npm start
```
Then this error occurs:
![error1](https://user-images.githubusercontent.com/25143884/49634898-fd532f80-fa38-11e8-8641-e67a1f9ced87.png)

Is this a bug of npm? This error appears only when I use `npm install`, but ok when use `yarn install`.

**Comment by ndbroadbent** [comment]
Hi @MmmmyPh, thanks for reporting that issue! This is happening because NPM installed the latest version of webpack, and `react-scripts` depends on an older version. 

I added the `webpack` dependency because I was trying to fix these warnings:

```
warning "craco-less > css-loader@1.0.1" has unmet peer dependency "webpack@^4.0.0".
warning "craco-less > less-loader@4.1.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
```

I also tried adding it under `peerDependencies` but that just made it worse:

```
warning "craco-less > css-loader@1.0.1" has unmet peer dependency "webpack@^4.0.0".
warning "craco-less > less-loader@4.1.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > craco-less@1.2.2" has unmet peer dependency "webpack@^4.0.0".
```

I think this might be happening because NPM's dependency resolution is not very smart, so maybe it sees `^4.0.0` and decides to install the latest version. Any maybe yarn is a bit smarter and installs the proper version required by `react-scripts`.

I [posted about this on StackOverflow to see if anyone has any ideas](https://stackoverflow.com/questions/53681694/how-can-i-resolve-the-webpack-unmet-peer-dependency-warning-for-my-create-reac).

**Comment by ndbroadbent** [comment]
But also, I think the key step here is that you delete `package-lock.json` (or `yarn.lock`). If you don't do that, then it should always install the locked version of `webpack`, instead of upgrading to the latest version.

If you use `npm install`, then just don't delete `package-lock.json`. And if you use `yarn install`, then don't delete `yarn.lock`. I think this should solve your issue.

**Comment by ndbroadbent** [comment]
Another follow-up comment: If the `yarn` dependency resolution is better and this never happens with `yarn install`, then I would just recommend that everyone uses `yarn`. 

Otherwise I would have to do a lot of work to manually keep the `webpack` version up to date whenever there's a new `react-scripts` version, instead of keeping the loose dependency. So I think everyone should just use `yarn`.
