### ISSUE TITLE
Duplicated packages webpack, css-loader, style-loader

### ISSUE THREAD

**Issue by yp** [FormAPI/craco-less#4]
If I install `craco-less` (either with `yarn` or `npm`, then a duplicated version of `webpack`, `css-loader`, and `style-loader` is installed, since the `craco-less` depends on them but with a different version range than `react-scripts`.
(I am aware that this is somehow related to #3.)
While apparently it did not cause any bug, I wonder if this could not be a source of obscure bugs in the future.
Are those dependencies only needed to "silence" the warnings reported on [StackOverflow](https://stackoverflow.com/questions/53681694/how-can-i-resolve-the-webpack-unmet-peer-dependency-warning-for-my-create-reac)? If this is the case, can you consider to drop them?

**Comment by ndbroadbent** [comment]
Yes, these dependencies are just to silence the npm/yarn warnings. 

I think I didn't realize that `css-loader` and `style-loader` were already dependencies of `react-scripts`, so it makes sense to remove those. After that, the only warning is:

```
warning " > less-loader@4.1.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
```

I've left [a comment on a yarn issue](https://github.com/yarnpkg/yarn/issues/4850#issuecomment-447277140). For now I'm just going to leave the webpack dependency, and it shouldn't cause any issues.

**Comment by ndbroadbent** [comment]
Hi again, thanks for opening this issue! I've decided to remove `css-loader` and `style-loader` from the dependencies. I've kept the `webpack` dependency, but I've pinned this to the same version as `react-scripts`, and I've [added a script](https://github.com/FormAPI/craco-less/blob/master/scripts/update_deps) to automate this. So whenever `react-scripts` changes their `webpack` version, I'll just run this script to use the same `webpack` version, and release a new version of `craco-less`.

I really hate warnings and this seemed to be the only way to fix it, so I think it's a good workaround for now.

**Comment by yp** [comment]
Thanks for the quick fix (even if it was not causing any real problem).
Do you mind to consider to move `craco` as a `peerDependency`?  Since it is a plugin for it, I think that it should specified as such (see, for example, the [yarn recommendations](https://yarnpkg.com/blog/2018/04/18/dependencies-done-right/)).

**Comment by ndbroadbent** [comment]
Oh right, yes that's a good idea! I also [just added a `peerDependency` for `craco-antd`](https://github.com/FormAPI/craco-antd/blob/master/package.json#L46-L48).

I think `react-scripts` should also be a `peerDependency`, because that will already be in the app's `package.json`.

The only problem is that this breaks the tests, because peer dependencies are not installed when you run `yarn install` in the `craco-less` repo. So I guess I also need to add them as `devDependencies`, which are only used for tests. A bit weird to include them in two places, but I think that's the right way to do it for now. I found [this open issue about it in the yarn repo](https://github.com/yarnpkg/yarn/issues/1503).

I also had to do that for the `craco-antd` package, which depends on `craco-less`. (Adding `@craco/craco` and `react-scripts` to both `devDependencies` and `peerDependencies`.)

So this seems to work pretty well and doesn't give any warnings. Thanks!
